---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &OrgIM
    Name: OrgIMMSP
    ID: OrgIMMSP
    MSPDir: crypto-config/peerOrganizations/im.example.com/msp
    AnchorPeers:
      - Host: peer0.im.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgIMMSP.admin', 'OrgIMMSP.peer', 'OrgIMMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgIMMSP.admin', 'OrgIMMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgIMMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgIMMSP.peer')"

  - &OrgWPI
    Name: OrgWPIMSP
    ID: OrgWPIMSP
    MSPDir: crypto-config/peerOrganizations/wpi.example.com/msp
    AnchorPeers:
      - Host: peer0.wpi.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgWPIMSP.admin', 'OrgWPIMSP.peer', 'OrgWPIMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgWPIMSP.admin', 'OrgWPIMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgWPIMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgWPIMSP.peer')"

  - &OrgHDW
    Name: OrgHDWMSP
    ID: OrgHDWMSP
    MSPDir: crypto-config/peerOrganizations/hdw.example.com/msp
    AnchorPeers:
      - Host: peer0.hdw.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgHDWMSP.admin', 'OrgHDWMSP.peer', 'OrgHDWMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgHDWMSP.admin', 'OrgHDWMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgHDWMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgHDWMSP.peer')"

  - &OrgSC
    Name: OrgSCMSP
    ID: OrgSCMSP
    MSPDir: crypto-config/peerOrganizations/sc.example.com/msp
    AnchorPeers:
      - Host: peer0.sc.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgSCMSP.admin', 'OrgSCMSP.peer', 'OrgSCMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgSCMSP.admin', 'OrgSCMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgSCMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgSCMSP.peer')"

  - &OrgSPI
    Name: OrgSPIMSP
    ID: OrgSPIMSP
    MSPDir: crypto-config/peerOrganizations/spi.example.com/msp
    AnchorPeers:
      - Host: peer0.spi.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgSPIMSP.admin', 'OrgSPIMSP.peer', 'OrgSPIMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgSPIMSP.admin', 'OrgSPIMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgSPIMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgSPIMSP.peer')"

  - &OrgMO
    Name: OrgMOMSP
    ID: OrgMOMSP
    MSPDir: crypto-config/peerOrganizations/mo.example.com/msp
    AnchorPeers:
      - Host: peer0.mo.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgMOMSP.admin', 'OrgMOMSP.peer', 'OrgMOMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgMOMSP.admin', 'OrgMOMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgMOMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgMOMSP.peer')"

  - &OrgRO
    Name: OrgROMSP
    ID: OrgROMSP
    MSPDir: crypto-config/peerOrganizations/ro.example.com/msp
    AnchorPeers:
      - Host: peer0.ro.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgROMSP.admin', 'OrgROMSP.peer', 'OrgROMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgROMSP.admin', 'OrgROMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgROMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgROMSP.peer')"

  - &OrgEC1
    Name: OrgEC1MSP
    ID: OrgEC1MSP
    MSPDir: crypto-config/peerOrganizations/ec1.example.com/msp
    AnchorPeers:
      - Host: peer0.ec1.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgEC1MSP.admin', 'OrgEC1MSP.peer', 'OrgEC1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgEC1MSP.admin', 'OrgEC1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgEC1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgEC1MSP.peer')"

  - &OrgEC2
    Name: OrgEC2MSP
    ID: OrgEC2MSP
    MSPDir: crypto-config/peerOrganizations/ec2.example.com/msp
    AnchorPeers:
      - Host: peer0.ec2.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgEC2MSP.admin', 'OrgEC2MSP.peer', 'OrgEC2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgEC2MSP.admin', 'OrgEC2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgEC2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgEC2MSP.peer')"

  - &OrgEC3
    Name: OrgEC3MSP
    ID: OrgEC3MSP
    MSPDir: crypto-config/peerOrganizations/ec3.example.com/msp
    AnchorPeers:
      - Host: peer0.ec3.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgEC3MSP.admin', 'OrgEC3MSP.peer', 'OrgEC3MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgEC3MSP.admin', 'OrgEC3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgEC3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgEC3MSP.peer')"




Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.example.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.example.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  BatchTimeout: 500ms
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# ================================================================
# PROFILES
# ================================================================
Profiles:
  # Profiles for System Channel
  SystemChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *ApplicationCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *OrgIM
          - *OrgWPI
          - *OrgHDW
          - *OrgSC
          - *OrgSPI
          - *OrgMO
          - *OrgRO
          - *OrgEC1
          - *OrgEC2
          - *OrgEC3

  # Profiles for Warehouse Channel
  WarehouseChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrgIM
        - *OrgWPI
        - *OrgHDW
        - *OrgMO
        - *OrgRO
        - *OrgEC1
        - *OrgEC2
        - *OrgEC3

      Capabilities:
        <<: *ApplicationCapabilities

  # Profiles for Study Channel
  StudyChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrgSC
        - *OrgSPI
        - *OrgMO
        - *OrgRO
        - *OrgEC1
        - *OrgEC2
        - *OrgEC3
      Capabilities:
        <<: *ApplicationCapabilities
